services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: nph
      POSTGRES_USER: nph
      POSTGRES_PASSWORD: nph
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nph -d nph"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://nph:nph@postgres:5432/nph?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"
  worker:
    build:
      context: .
      dockerfile: infra/docker/worker.Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://nph:nph@postgres:5432/nph?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    depends_on:
      - api
    ports:
      - "3000:3000"
  gateway:
    image: nginx:1.27-alpine
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./infra/observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:11.2.2
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  postgres_data:
  grafana_data:
