events {}

http {
  upstream api_upstream {
    server api:3001;
  }

  upstream web_upstream {
    server web:3000;
  }

  server {
    listen 8080;

    location /v1/ {
      proxy_pass http://api_upstream/v1/;
    }

    location /docs {
      proxy_pass http://api_upstream/docs;
    }

    location / {
      proxy_pass http://web_upstream;
    }
  }
}
